version: '3.7'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./supp:/supp
    entrypoint: sh "/entrypoint.sh"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A supp worker -l info
    volumes:
      - ./supp:/supp
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web
volumes:
  pgdata:
