# Generated by Django 4.0.1 on 2022-01-12 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('queue', 'В очереди'), ('work', 'Принят в работу'), ('answered', 'Отвечен'), ('resolved', 'Вопрос решён')], default='queue', max_length=150, verbose_name='Статус')),
                ('type', models.TextField(max_length=150, verbose_name='Тип запроса')),
                ('title', models.CharField(max_length=250, verbose_name='Тема')),
                ('descripion', models.TextField(max_length=900, verbose_name='Описание проблемы')),
                ('updated_time', models.DateTimeField(verbose_name='Последнее обновление')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True, verbose_name='Дата создания')),
                ('text', models.TextField(max_length=900, verbose_name='Сообщение')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
