# Generated by Django 4.0.1 on 2022-02-01 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_message_created_time_alter_message_ticket_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='descripion',
            new_name='description',
        ),
    ]
