# Generated by Django 4.0.1 on 2022-02-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('queue', 'В очереди'), ('work', 'Принят в работу'), ('answered', 'Отвечен'), ('resolved', 'Вопрос решён')], max_length=150, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.TextField(blank=True, choices=[('finance', 'Финансы'), ('technical', 'Технические вопросы'), ('report', 'Жалобы и предложения'), ('other', 'Иные вопросы')], max_length=150, verbose_name='Тип запроса'),
        ),
    ]
