# Generated by Django 4.0.1 on 2022-02-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticket_status_alter_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.TextField(choices=[('finance', 'Финансы'), ('technical', 'Технические вопросы'), ('report', 'Жалобы и предложения'), ('other', 'Иные вопросы')], max_length=150, verbose_name='Тип запроса'),
        ),
    ]
