# Generated by Django 4.0.1 on 2022-02-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('queue', 'В очереди'), ('work', 'Принят в работу'), ('answered', 'Отвечен'), ('resolved', 'Вопрос решён')], default='queue', max_length=150, verbose_name='Статус'),
        ),
    ]
